### PR TITLE
Add array tests

### PR DESCRIPTION
**Pull request by briancavalier**
Add unit tests, type signatures, and minimal comment docs

### CODE REVIEW

**Comment by briancavalier** [comment]
Still need to add tests for a few more, but getting close.

**Comment by TylorS** [comment]
Looks good :+1:

**Comment by briancavalier** [comment]
Thanks!

> Return true if x is array-like

In fact, [iff means "if and only if"](https://en.wikipedia.org/wiki/If_and_only_if), so that was intentional!

**Comment by TylorS** [comment]
:+1: Ahhh okay

**Comment by briancavalier** [comment]
:boom:

**Pull request merged**
