### PR TITLE
Use power-assert

### PR DESCRIPTION
**Pull request by briancavalier**
This also uses `babel-plugin-empower-assert` to _transparently_ upgrade `assert` to `power-assert`.  I'm not sure if that's a better approach than explicitly importing `power-assert`.  I kinda like it, tho, since it meant zero code changes ... only configuration changes.

### CODE REVIEW

**Comment by twada** [comment]
Hi, I recommend [babel-preset-power-assert](https://github.com/power-assert-js/babel-preset-power-assert). That's a babel preset for all power-assert plugins.

**Comment by briancavalier** [comment]
Hey @twada, thanks!  Looks like I can replace both babel-plugin-empower-assert and babel-plugin-espower by using babel-preset-power-assert.  That's cool.

When I was reading the [power-assert README and docs](https://github.com/power-assert-js/power-assert), it wasn't clear to me whether I should pick `babel-plugin-espower` or `babel-preset-power-assert`.  Just a suggestion, but perhaps there's a way to add a bit more guidance to the docs, i.e. clarify the conditions under which someone might pick one or the other.

**Comment by twada** [comment]
@briancavalier 

> When I was reading the power-assert README and docs, it wasn't clear to me whether I should pick babel-plugin-espower or babel-preset-power-assert. Just a suggestion, but perhaps there's a way to add a bit more guidance to the docs, i.e. clarify the conditions under which someone might pick one or the other.

Totally agreed. `babel-preset-power-assert` is the newest one and there is still much room for document improvement. Sorry for inconvenience.

**Comment by briancavalier** [comment]
Great, thanks @twada!  I'm really liking power-assert so far.

**Pull request merged**
